### ISSUE TITLE
Stack not ending is Set Num  over 1

### ISSUE THREAD

**Issue by cru67** [ReallySmall/Stackduino-v0.1---v1.1#3]
Hello! 
I have a problem. If I put "set num step" on 1 and switch on "return to start", everything like it works shall. Stackudino makes 1 step and a picture and returns into the starting point. I put on "set num step" jump over 1, either no more stop is carried out and a step after the others till I is carried out either the stack breaks off or an end switch is met.

Greetings

**Comment by ReallySmall** [comment]
Hello! Sorry for the delay in reply.

I'm puzzled by your being able to set num step to a value of '1' - the minimum value you should be seeing on the screen is '10', and it should increment in multiples of 10.

Can you clarify on that please?
Cheers

**Comment by cru67** [comment]
Hello! 
Since my English is not so good, I use a translation programme. I hope it is to some extent nevertheless understandable. 

Since I have the problem and such a couple of modifications in this have experimented I a little. I am also on this one

working step pushed with the 1 picture. 



int slice_depth = 1; //default number of microns stepper motor should make between pictures
int slices = 10; //default total number of pictures to take
int stepper_speed = 1000; //delay in microseconds between motor steps, governing motor speed in stack
int unit_of_measure = 2; //whether to use microns, mm or cm when making steps
int unit_of_measure_multiplier = 1000; //multiplier to factor into step signals (1, 1000 or 10000) depending on unit of measure used
boolean update_screen = true; //whether to print to the lcd with new or updated information



      case 2: //this menu screen changes the number of pictures to take in the stack
        if (rotary_button_state == LOW) { //if rotary encoder button is toggled within a menu, enabled editing of menu variable with encoder
          encoder_update(slices, 1, 5000, 1);
        }

        if (update_screen){  //the screen hardware is slow so only print to it when something changes
          lcd.clear();
          lcd.setCursor(0, 0);
          lcd.print("Set num steps:");
          lcd.setCursor(0, 1);
          lcd_front_load(slices); //frontload with correct number of zeroes and print to screen
          update_screen = false;
        } 

        break;

 

I have the sketch of the Nov 19 2014 with the Arduino version 1.0.5 version tried meanwhile and everything works fine also with the above changes. 

Cheers

----- Original Message -----

**Comment by sanjaykashyap** [comment]
Hi
cru67,
A very warm happy New Year.
I am unable to get a PCB for Stackduino, so can u help me in buying a
couple of the PCB from the place you have bought.

**Comment by cru67** [comment]
Hi
Happy New Year to.
I have not bought PCB especially for Stackudino  .I use a Arduino UNO . I have taken something like this  http://www.ebay.de/itm/3x-Strip-Board-PCB-Vero-Prototyping-3-hole-Island-High-Quality-Fast-Delivery-/111573420969?hash=item19fa4b4ba9:g:gHgAAOxyaTxTTmls  and built a Shield. Everything in a flying wiring.

**Comment by ReallySmall** [comment]
Hi all,

I built an early version in a similar way too: https://www.flickr.com/photos/reallysmall/8387920114/in/album-72157632341602394/
